services:
  php:
    image: dunglas/frankenphp:1.3-php8.4
    restart: unless-stopped
    network_mode: host
    ports:
      - "8333:80" # HTTP
      - "9333:443" # HTTPS
      - "9333:443/udp" # HTTP/3
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SERVER_NAME=${SERVER_NAME:-localhost}
      - APP_LOG_DIR=${APP_LOG_DIR:-/app/var/log}

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
