services:
  php:
    image: dunglas/frankenphp:1.3-php8.4
    restart: always
    ports:
      - "8333:80" # HTTP
      - "9333:443" # HTTPS
      - "9333:443/udp" # HTTP/3
    environment:
      - FRANKENPHP_CONFIG="worker ./public/index.php"
      - APP_RUNTIME=Runtime\FrankenPhpSymfony\Runtime
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
